name: Mypy Type Check

on: [push, pull_request]

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry==1.8.5

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run mypy
        run: poetry run mypy .