name: Check Types with Mypy

on: [push, pull_request]

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t image .

      - name: Run mypy
        run: >
          docker run --rm 
          -v "${{ github.workspace }}:/app" 
          mypy-check 
          poetry run mypy .